"""Stream type classes for tap-sellercloud."""

from pathlib import Path
from typing import Any, Dict, Optional, Union, List, Iterable

from singer_sdk import typing as th  # JSON Schema typing helpers

from tap_sellercloud.client import SellercloudStream


class PurchaseOrdersStream(SellercloudStream):
    """Define custom stream."""

    name = "purchase_orders"
    path = "/PurchaseOrders"
    primary_keys = ["ID"]
    replication_key = "LastRevisedOn"
    replication_key_field = "model.updatedDateFrom"

    schema = th.PropertiesList(
        th.Property("ID", th.NumberType),
        th.Property("EmailSentCount", th.NumberType),
        th.Property("DisableInventoryCount", th.BooleanType),
        th.Property("POType", th.NumberType),
        th.Property("CancelledPOID", th.NumberType),
        th.Property("TotalBalance", th.NumberType),
        th.Property("TotalBalanceNotReceivedGood", th.NumberType),
        th.Property("VendorID", th.NumberType),
        th.Property("PurchaseTitle", th.StringType),
        th.Property("CreatedOn", th.DateTimeType),
        th.Property("CreatedBy", th.NumberType),
        th.Property("OrderTotal", th.NumberType),
        th.Property("TaxTotal", th.NumberType),
        th.Property("ShippingTotal", th.NumberType),
        th.Property("GrandTotal", th.NumberType),
        th.Property("DateOrdered", th.DateTimeType),
        th.Property("LastRevisedOn", th.DateTimeType),
        th.Property("RevisedBy", th.NumberType),
        th.Property("PurchaseOrderStatus", th.NumberType),
        th.Property("PaymentStatus", th.NumberType),
        th.Property("ExtraCharges", th.NumberType),
        th.Property("TotalRefunded", th.NumberType),
        th.Property("PurchaseOrdersShippingStatus", th.NumberType),
        th.Property("TrackingNumber", th.StringType),
        th.Property("TrackingNumbers", th.CustomType({"type": ["array", "string"]})),
        th.Property("ShippedOn", th.StringType),
        th.Property("CourierService", th.StringType),
        th.Property("PurchaseOrdersPriority", th.NumberType),
        th.Property("ReceivingStatus", th.NumberType),
        th.Property("CompanyID", th.NumberType),
        th.Property("PurchaseOrdersApproved", th.BooleanType),
        th.Property("DropShipOrderNumber", th.NumberType),
        th.Property("VendorInvoiceNumber", th.StringType),
        th.Property("VendorInvoiceFileName", th.StringType),
        th.Property("VendorInvoiceFileNameOriginal", th.StringType),
        th.Property("Invoices", th.CustomType({"type": ["array", "string"]})),
        th.Property("Memo", th.StringType),
        th.Property("ExpectedDeliveryDate", th.DateTimeType),
        th.Property("DiscountTotal", th.NumberType),
        th.Property("bExported", th.BooleanType),
        th.Property("DisplayName", th.StringType),
        th.Property("CM", th.NumberType),
        th.Property("NotesCount", th.NumberType),
        th.Property("PaidOn", th.StringType),
        th.Property("UnitCounts", th.NumberType),
        th.Property("PurchaseOrderCreditMemo", th.BooleanType),
        th.Property("WarehouseID", th.NumberType),
        th.Property("Items", th.CustomType({"type": ["array", "string"]})),
        th.Property("RequestedShippingCarrier", th.StringType),
        th.Property("RequestedShippingService", th.StringType),
        th.Property("ShipToAddress", th.CustomType({"type": ["object", "string"]})),
    ).to_dict()


class CatalogStream(SellercloudStream):
    """Define custom stream."""

    name = "catalog"
    path = "/Catalog"
    primary_keys = ["ID"]
    replication_key = "LastModifiedDate"
    replication_key_field = "model.lastUpdatedFrom"

    schema = th.PropertiesList(
        th.Property("ImageUrl", th.StringType),
        th.Property("Weight", th.NumberType),
        th.Property("ShippingWeight", th.NumberType),
        th.Property("WeightOz", th.NumberType),
        th.Property("PackageWeightLbs", th.NumberType),
        th.Property("PackageWeightOz", th.NumberType),
        th.Property("LocationNotes", th.StringType),
        th.Property("eBayCategory", th.StringType),
        th.Property("eBayStoreCategory", th.StringType),
        th.Property("eBayItemCondition", th.StringType),
        th.Property("MAPPrice", th.NumberType),
        th.Property("ShadowOf", th.StringType),
        th.Property("AverageCost", th.NumberType),
        th.Property("Priority", th.IntegerType),
        th.Property("Rating", th.NumberType),
        th.Property("ProductName", th.StringType),
        th.Property("ShortDescription", th.StringType),
        th.Property("LongDescription", th.StringType),
        th.Property("Buyer", th.StringType),
        th.Property("ASIN", th.StringType),
        th.Property("GTIN", th.StringType),
        th.Property("QtySold15", th.NumberType),
        th.Property("QtySold30", th.NumberType),
        th.Property("QtySold60", th.NumberType),
        th.Property("QtySold90", th.NumberType),
        th.Property("QtySold180", th.NumberType),
        th.Property("QtySold365", th.NumberType),
        th.Property("QtySoldYTD", th.NumberType),
        th.Property("IsEndOfLife", th.BooleanType),
        th.Property("ShippingCost", th.NumberType),
        th.Property("AggregatePhysicalQtyFBA", th.NumberType),
        th.Property("AggregatePhysicalQty", th.NumberType),
        th.Property("AggregateQty", th.NumberType),
        th.Property("ProductType", th.StringType),
        th.Property("DefaultVendor", th.StringType),
        th.Property("DefaultVendorSKU", th.StringType),
        th.Property("HomeCountryCode", th.NumberType),
        th.Property("Country", th.StringType),
        th.Property("AmazonMarketPlaceID", th.StringType),
        th.Property("OverstockGeneratedProductID", th.StringType),
        th.Property("ReverbListingID", th.IntegerType),
        th.Property("WalmartProductID", th.StringType),
        th.Property("WPID", th.StringType),
        th.Property("ItemPageURL", th.StringType),
        th.Property("CompanyName", th.StringType),
        th.Property("CompanyNameAbbreviation", th.StringType),
        th.Property("FirstKitChild", th.StringType),
        th.Property("WarehousePhysicalQty", th.NumberType),
        th.Property("WarehousePhysicalQtyValue", th.NumberType),
        th.Property("WarehouseReservedQtyValue", th.NumberType),
        th.Property("AggregatedQty", th.NumberType),
        th.Property("AggregatePhysicalSellableQtyIncludingPhysicalValue", th.NumberType),
        th.Property("ReservedQty", th.NumberType),
        th.Property("ReserveQtyTotalValue", th.NumberType),
        th.Property("PhysicalQty", th.NumberType),
        th.Property("AggregateNonSellableQty", th.NumberType),
        th.Property("StorePrice", th.NumberType),
        th.Property("ManufacturerSKU", th.StringType),
        th.Property("ManufacturerID", th.IntegerType),
        th.Property("BrandID", th.IntegerType),
        th.Property("ASINInActiveListing", th.StringType),
        th.Property("WeightLbs", th.NumberType),
        th.Property("UPC", th.StringType),
        th.Property("AmazonFBASKU", th.StringType),
        th.Property("NELiveInventory", th.NumberType),
        th.Property("NEBizInventory", th.NumberType),
        th.Property("WebsiteViewURL", th.StringType),
        th.Property("WishProductID", th.StringType),
        th.Property("FulfilledBy", th.IntegerType),
        th.Property("SalesRank", th.IntegerType),
        th.Property("AmazonProductCondition", th.IntegerType),
        th.Property("AmazonCondition", th.StringType),
        th.Property("MainProductID", th.StringType),
        th.Property("FixedPriceQuantity", th.NumberType),
        th.Property("BuyItNowPrice", th.NumberType),
        th.Property("ShippingTemplateID", th.StringType),
        th.Property("ListPrice", th.NumberType),
        th.Property("SalePrice", th.NumberType),
        th.Property("SalePriceStartDate", th.StringType),
        th.Property("SalePriceEndDate", th.StringType),
        th.Property("DropShipMode", th.IntegerType),
        th.Property("eBayCategory1ID", th.StringType),
        th.Property("eBayCategory1Name", th.StringType),
        th.Property("eBayTopTitle", th.StringType),
        th.Property("ProductTitleCount", th.NumberType),
        th.Property("DescriptionTemplateID", th.StringType),
        th.Property("ebayItemID", th.StringType),
        th.Property("ebaySiteCode", th.IntegerType),
        th.Property("ProductConditionName", th.StringType),
        th.Property("NotesCount", th.NumberType),
        th.Property("OrderReserveTotal", th.NumberType),
        th.Property("VendorOfProduct", th.StringType),
        th.Property("VendorPrice", th.NumberType),
        th.Property("ReplacementQty", th.NumberType),
        th.Property("WarehouseName", th.StringType),
        th.Property("IsSellAble", th.BooleanType),
        th.Property("WarehouseCount", th.NumberType),
        th.Property("CompanyID", th.IntegerType),
        th.Property("WebEnabled", th.BooleanType),
        th.Property("BuyDotComEnabled", th.BooleanType),
        th.Property("MagentoEnabled", th.BooleanType),
        th.Property("SearsEnabled", th.BooleanType),
        th.Property("PriceGrabberEnabled", th.BooleanType),
        th.Property("OverStockEnabled", th.BooleanType),
        th.Property("PriceFallEnabled", th.BooleanType),
        th.Property("UnbeatableSalesEnabled", th.BooleanType),
        th.Property("eBayEnabled", th.BooleanType),
        th.Property("AmazonEnabled", th.BooleanType),
        th.Property("WayfairEnabled", th.BooleanType),
        th.Property("VendorCentralEnabled", th.BooleanType),
        th.Property("BonanzaEnabled", th.BooleanType),
        th.Property("SmartBargainsEnabled", th.BooleanType),
        th.Property("ATGStoresEnabled", th.BooleanType),
        th.Property("BestBuyEnabled", th.BooleanType),
        th.Property("BestBuyDsEnabled", th.BooleanType),
        th.Property("KohlsEnabled", th.BooleanType),
        th.Property("HomeDepotEnabled", th.BooleanType),
        th.Property("StaplesEnabled", th.BooleanType),
        th.Property("MeijerEnabled", th.BooleanType),
        th.Property("OneStopPlusEnabled", th.BooleanType),
        th.Property("SonsiEnabled", th.BooleanType),
        th.Property("KMartEnabled", th.BooleanType),
        th.Property("ElevenMainEnabled", th.BooleanType),
        th.Property("GroupOnGoodsEnabled", th.BooleanType),
        th.Property("GrouponMarketplaceEnabled", th.BooleanType),
        th.Property("WalmartEnabled", th.BooleanType),
        th.Property("WalmartAPIEnabled", th.BooleanType),
        th.Property("WishEnabled", th.BooleanType),
        th.Property("JETEnabled", th.BooleanType),
        th.Property("EtsyEnabled", th.BooleanType),
        th.Property("FingerHutEnabled", th.BooleanType),
        th.Property("TopHatterEnabled", th.BooleanType),
        th.Property("TangaEnabled", th.BooleanType),
        th.Property("TargetEnabled", th.BooleanType),
        th.Property("NewEggDotComEnabled", th.BooleanType),
        th.Property("NewEggBizEnabled", th.BooleanType),
        th.Property("YahooStoreEnabled", th.BooleanType),
        th.Property("HayneedleEnabled", th.BooleanType),
        th.Property("ReverbEnabled", th.BooleanType),
        th.Property("DropShipCentralEnabled", th.BooleanType),
        th.Property("DrugStoresEnabled", th.BooleanType),
        th.Property("CdiscountEnabled", th.BooleanType),
        th.Property("BedBathAndBeyondEnabled", th.BooleanType),
        th.Property("ShopHQEnabled", th.BooleanType),
        th.Property("GoogleShoppingEnabled", th.BooleanType),
        th.Property("HouzzEnabled", th.BooleanType),
        th.Property("BackmarketEnabled", th.BooleanType),
        th.Property("IsMatrixParent", th.BooleanType),
        th.Property("MerchantSKU", th.StringType),
        th.Property("AmazonMerchantSKU", th.StringType),
        th.Property("WayfairMerchantSKU", th.StringType),
        th.Property("WebsiteProductID", th.StringType),
        th.Property("ActiveRebateID", th.NumberType),
        th.Property("ActiveRebateValue", th.NumberType),
        th.Property("ActiveRebateDeductFromItemCost", th.NumberType),
        th.Property("DeductFromItemCostType", th.NumberType),
        th.Property("BrandName", th.StringType),
        th.Property("DateCreated", th.DateTimeType),
        th.Property("ActiveStatus", th.StringType),
        th.Property("LightspeedPOSEnabled", th.BooleanType),
        th.Property("Status", th.IntegerType),
        th.Property("InventoryDependantOption", th.IntegerType),
        th.Property("OnOrder", th.NumberType),
        th.Property("AmazonPrice", th.NumberType),
        th.Property("VendorID", th.IntegerType),
        th.Property("VendorVisible", th.BooleanType),
        th.Property("LastAggregateDate", th.DateTimeType),
        th.Property("LastModifiedDate", th.DateTimeType),
        th.Property("AmazonMarketplace", th.StringType),
        th.Property("OnBackOrder", th.NumberType),
        th.Property("BackOrderVisible", th.BooleanType),
        th.Property("WholeSalePrice", th.NumberType),
        th.Property("WholeSalePriceVisible", th.BooleanType),
        th.Property("SitePrice", th.NumberType),
        th.Property("SiteCost", th.NumberType),
        th.Property("IsKit", th.BooleanType),
        th.Property("SiteCostVisible", th.BooleanType),
        th.Property("LastCost", th.NumberType),
        th.Property("LastCostVisible", th.BooleanType),
        th.Property("ShowPriorityAndRatingDelta", th.BooleanType),
        th.Property("InventoryAvailableQty", th.NumberType),
        th.Property("ChildProducts", th.StringType),
        th.Property("AmazonStoreStatus", th.BooleanType),
        th.Property("EnabledOnChannels", th.ArrayType(th.IntegerType)),
        th.Property("ChannelPreviews", th.ArrayType(
            th.ObjectType(
                th.Property("Channel", th.IntegerType),
                th.Property("URL", th.StringType),
            )
        )),
        th.Property("AmazonEnableBOPISProduct", th.BooleanType),
        th.Property("ID", th.StringType),
        th.Property("CustomColumns", th.ArrayType(
            th.ObjectType(
                th.Property("ID", th.IntegerType),
                th.Property("DataType", th.IntegerType),
                th.Property("DataLength", th.IntegerType),
                th.Property("IsDropDownColumn", th.BooleanType),
                th.Property("IsDropDownCustomTextAllowed", th.BooleanType),
                th.Property("IsDropDownAllowMultipleSelection", th.BooleanType),
                th.Property("ClientID", th.IntegerType),
                th.Property("NewValue", th.StringType),
                th.Property("AllowHTMLPopup", th.BooleanType),
                th.Property("IsRequired", th.BooleanType),
                th.Property("ColumnName", th.StringType),
                th.Property("DisplayName", th.StringType),
                th.Property("Value", th.CustomType({"type": ["string", "number", "boolean"]})),
            )
        ))

    ).to_dict()
